[package]
name = "proj2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mockall = "0.11"
parameterized = "1"
rand = "0.8"
bytes = "*"
hex = "0.4.3"
dns-message-parser = "0.7.0"
regex = "1.10.2"
